// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qdscirbsypclxzlojgug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkc2NpcmJzeXBjbHh6bG9qZ3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExODI4OTgsImV4cCI6MjA3Njc1ODg5OH0.54Wfn0A8rh7VEnAfceZ3u3Kwdlb9z3aJcbgjexwb-Zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);