// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://aijiyiiirkzfaygubene.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpaml5aWlpcmt6ZmF5Z3ViZW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MTkzODcsImV4cCI6MjA3NzE5NTM4N30.Mi_OlbnsmGGby8-Ayg0YNumtOpWog2p9PpAm7rlC0IM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);